### ISSUE TITLE
Theme should be converted to Radix 3 / Bootstrap 3

### ISSUE THREAD

**Issue by lsolesen** [vih/ketsjup-theme#5]
This is a subtheme of Chef. Right now Chef is only for Bootstrap 3. Chef needs to be updated to Radix 3. Then this theme needs to be updated for Radix 3 as well.

**Comment by shadcn** [comment]
Working on this right now.

**Comment by lsolesen** [comment]
When will this be ready?

**Comment by lsolesen** [comment]
E.T.A.?

**Comment by lsolesen** [comment]
Reassigning to @mglaman. I will give you commit access to the Chef theme. The recent changes in Panopoly where Radix Layouts are included has messed up most of the site layout on vies.dk. I need this fixed ASAP :)

**Comment by lsolesen** [comment]
Hm, seems I do not have access to grant other developers commit access to Chef. @arshad can you add @mglaman, so I can have this issue resolved?

Otherwise, @mglaman you can create patches, and I will commit them.

If it is easier to simply start from scratch, you can do that also for ketsjup-theme in a 3.x-branch? It doesn't have to look exactly like now.

**Comment by shadcn** [comment]
@lsolesen you mean to this repo? https://github.com/arshad/chef

**Comment by lsolesen** [comment]
@arshad I meant to http://drupal.org/project/chef - As I can see the work is not finished yet, and I am guessing you are too busy at the moment?

**Comment by lsolesen** [comment]
Here is the problems introduced with recent versions of Panopoly obvious:

![vies-problems-layout](https://cloud.githubusercontent.com/assets/148026/6413512/85388ad2-be90-11e4-93d5-ef4b494b2486.png)

This is based on https://github.com/vih/vies-build:

```
projects[radix][type] = theme
projects[radix][download][type] = git
projects[radix][download][revision] = 7082e64
projects[radix][download][branch] = 7.x-2.x

projects[chef][subdir] = contrib
projects[chef][version] = 1.x-dev
projects[chef][download][type] = git
projects[chef][download][revision] = 8235b76
projects[chef][download][branch] = 7.x-1.x
; not including the issue number in the array as they need to run in this order
projects[chef][patch][] = http://drupal.org/files/issues/issue-2250837.patch
projects[chef][patch][] = http://drupal.org/files/issues/issue-2118989_0.patch

projects[ketsjup][type] = "theme"
projects[ketsjup][download][type] = "git"
projects[ketsjup][download][url] = "https://github.com/vih/ketsjup-theme.git"
projects[ketsjup][download][branch] = "7.x-1.x"
projects[ketsjup][download][revision] = "157d699763629fd52e9240b141171a5e510e4f44"
```

**Comment by lsolesen** [comment]
@cornifex The ketsjup-theme does not have to be based on Chef - and the fix do not have to be pixel perfect as long as it looks better :)

**Comment by cornifex** [comment]
@lsolesen I made some good progress on this over yesterday and today. Currently, the navbar and footer need work. Other than that, minor style tweaks here and there and this should be wrapped up

**Comment by lsolesen** [comment]
Can I update the live site, so we can begin working out quirks?

**Comment by cornifex** [comment]
@lsolesen I don't think it's ready yet. I should have the nav and footer kinks worked out today

**Comment by lsolesen** [comment]
Closing this as it is already in production.
